// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/ApiSplit.tsx": () => import("../components/mockups/hero-variants/ApiSplit.tsx"),
  "./components/mockups/hero-variants/LightTrust.tsx": () => import("../components/mockups/hero-variants/LightTrust.tsx"),
  "./components/mockups/hero-variants/PhoneAlive.tsx": () => import("../components/mockups/hero-variants/PhoneAlive.tsx")
};
